import { AppProps } from "next/app";
import Head from "next/head";
import "../styles/globals.css";
import ym, {YMInitializer} from "react-yandex-metrika"

function MyApp({ Component, pageProps, router }: AppProps): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="preconnect" href="https://mc.yandex.ru" />
        <meta property='og:url' content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
        <meta property='og:locale' content='ru_RU' />
      </Head>
      <YMInitializer 
        accounts={[]}
        options={{webvisor: true, defer: true}}
        version="2"
      />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
